version: "3.9"

volumes:
  rpc_prometheus_data: {}

networks:
  rpc_monitoring:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: rpc_prometheus
    volumes:
       - type: volume
         source: rpc_prometheus_data
         target: /prometheus
       - type: bind
         source: ./prometheus
         target: /etc/prometheus
         read_only: true 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - "9690:9090"
    networks:
      - rpc_monitoring
    restart: always

  rpc_exporter:
    build: .
    container_name: rpc_exporter
    ports:
      - "9600:9300"
    restart: always
    environment:
      - FLASK_DEBUG=true
    networks:
      - rpc_monitoring
    entrypoint: ["/usr/bin/rpc_exporter"]

  alertmanager:
    image: prom/alertmanager:latest
    container_name: rpc_alertmanager
    networks:
      - rpc_monitoring
    ports:
      - "9693:9093"
    volumes:
      - type: bind
        source: ./prometheus/alert_manager
        target: /etc/alertmanager
        read_only: true
    command: [
      '--config.file=/etc/alertmanager/alertmanager.yml',
      '--log.level=debug',
    ]
    hostname: 'alertmanager'
    restart: always