global:
  resolve_timeout: 1m

templates: 
- 'templates/*'

route:
  group_by: ['...']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
  
  routes:
    - receiver: 'discord'
      group_by: ['...']

  receiver: discord

receivers:
  - name: discord
    discord_configs:
      - webhook_url: YOUR_WEBHOOK_HERE
        title: '{{ template "discord.title" . }}'
        message: '{{ template "discord.message" . }}'