groups:
  - name: rpc-monitor
    rules:
      - alert: RpcStopSyncing
        expr: miss_rate > 0.15
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "miss rate hit 15%"
          description: "Miss rate hit 15%, fix urgently {{ $labels.instance }} before it hits 31%"

      - alert: RpcGotPanicError
        expr: delta(miss_rate[5m]) > 6 and miss_rate > 0.5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "miss rate is going up"
          description: "Miss rate is going up, check {{ $labels.instance }}"

      - alert: PriceFeederIsDown
        expr: delta(last_block_vote[5m]) < 40
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "oracle is down"
          description: "Last vote block hasn't changed for last 5m, check {{ $labels.instance }}"

      - alert: MissCounterGoingUp
        expr: delta(miss_counter[5m]) > 8
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "miss counter is going up"
          description: "One or more asset missed their vote, please check"