groups:
  - name: rpc-monitor
    rules:
      - alert: RpcCannotCatchUp
        expr: rpc_status == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "RPC Node is not synced"
          description: "RPC Node is not synced"

      - alert: RpcStopSyncing
        expr: delta(rpc_sync_blocks[5m]) < 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "RPC Node has been stopped syncing"
          description: "RPC Node probably got AppHash"

      - alert: RpcGotPanicError
        expr: rpc_status{error!=""} == 0 OR rpc_sync_blocks{error!=""} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "RPC Node has been stopped working due to panic"
          description: "RPC Node has been stopped working due to panic"